= Bases de datos II - OrientDB
v1, {docdate}
:toc:
:title-page:
:toc-title: Secciones
:numbered:
:source-highlighter: highlight.js
:tabsize: 4
:nofooter:
:pdf-page-margin: [3cm, 3cm, 3cm, 3cm]

== Introducción

OrientDB es una bases de datos NoSQL de código abierto orientado a documentos y grafos desarrollada en Java.

== Origen

Fue desarrollado por OrientDB Ltd. y está diseñado para ser una base de datos NoSQL de alto rendimiento y escalable.

== Casos de éxito

== Características principales

- Taxonomía: OrientDB es multi-modelo, lo que significa que admite múltiples modelos de datos, incluyendo documentos, grafos, clave-valor y objetos.

- Escalabilidad: OrientDB es escalable y puede funcionar en un clúster distribuido, lo que permite la distribución de datos en varios nodos para manejar grandes volúmenes de información.

- Transacciones ACID: OrientDB garantiza transacciones ACID (Atomicidad, Consistencia, Aislamiento y Durabilidad), lo que lo hace adecuado para aplicaciones que requieren alta integridad de datos.

- Compatibilidad: OrientDB es compatible con múltiples lenguajes de programación, incluyendo Java, Python y .NET.

== Diferencias con otras bases de datos

== Instalación y configuración

== Operaciones básicas

OrientDB es compatible con el conocido lenguaje de consultas SQL y soporta consultas en lenguaje Gremlin para trabajar con datos de grafo.

=== Crear clase

[source, sql]
----
CREATE CLASS Estudiante;
----

=== Agregar atributos

[source, sql]
----
CREATE PROPERTY Estudiante.legajo STRING;
CREATE PROPERTY Estudiante.nombre STRING;
CREATE PROPERTY Estudiante.apellido STRING;
CREATE PROPERTY Estudiante.nacimiento DATE;
----

=== Crear indice

[source, sql]
----
CREATE INDEX Estudiante.legajo UNIQUE;
----

=== Insert

Como en una base de datos relacional, se puede usar:

[source, sql]
----
INSERT INTO Estudiante (legajo, nombre, apellido) VALUES (1, 'Juan', 'Perez');
----

De otra forma:

[source, sql]
----
INSERT INTO Estudiante SET legajo = 1, nombre = 'Juan', apellido = 'Perez';
----

En la sintaxis de contenido JSON, se escribiría así:

[source, sql]
----
INSERT INTO Estudiante CONTENT {'legajo': 1, 'nombre': 'Juan', 'apellido': 'Perez'};
----

=== Delete

.Agrego 2 estudiantes más
[source, console]
----
orientdb {db=prueba}> INSERT INTO Estudiante CONTENT {'legajo': 2, 'nombre': 'Maria', 'apellido': 'Gonzalez'};

Inserted record '[Estudiante#22:2{legajo:2,nombre:Maria,apellido:Gonzalez} v1]' in 0.002000 sec(s).

orientdb {db=prueba}> INSERT INTO Estudiante CONTENT {'legajo': 3, 'nombre': 'Carlos', 'apellido': 'Ramirez'};

Inserted record '[Estudiante#23:1{legajo:3,nombre:Carlos,apellido:Ramirez} v1]' in 0.001000 sec(s).
----

.Muestro los datos
[source, console]
----
orientdb {db=prueba}> SELECT * FROM Estudiante;

+----+-----+----------+------+------+--------+
|#   |@RID |@CLASS    |legajo|nombre|apellido|
+----+-----+----------+------+------+--------+
|0   |#22:2|Estudiante|2     |Maria |Gonzalez|
|1   |#23:1|Estudiante|3     |Carlos|Ramirez |
|2   |#25:1|Estudiante|1     |Juan  |Perez   |
+----+-----+----------+------+------+--------+

3 item(s) found. Query executed in 0.003 sec(s).
----

.Elimino y muestro los datos
[source, console]
----
orientdb {db=prueba}> DELETE FROM Estudiante WHERE legajo = 2;

Delete record(s) '[{count:1}]' in 0.003000 sec(s).

orientdb {db=prueba}> SELECT * FROM Estudiante;

+----+-----+----------+------+------+--------+
|#   |@RID |@CLASS    |legajo|nombre|apellido|
+----+-----+----------+------+------+--------+
|0   |#23:1|Estudiante|3     |Carlos|Ramirez |
|1   |#25:1|Estudiante|1     |Juan  |Perez   |
+----+-----+----------+------+------+--------+

2 item(s) found. Query executed in 0.001 sec(s).
----

=== Update

[source, console]
----
orientdb {db=prueba}> SELECT * FROM Estudiante;

+----+-----+----------+------+------+--------+
|#   |@RID |@CLASS    |legajo|nombre|apellido|
+----+-----+----------+------+------+--------+
|0   |#23:1|Estudiante|3     |Carlos|Ramirez |
|1   |#25:1|Estudiante|1     |Juan  |Perez   |
+----+-----+----------+------+------+--------+

2 item(s) found. Query executed in 0.001 sec(s).
orientdb {db=prueba}> UPDATE Estudiante SET apellido = 'Rodriguez' WHERE legajo = 3;

Updated record(s) '[{count:1}]' in 0.008000 sec(s).

orientdb {db=prueba}> SELECT * FROM Estudiante;

+----+-----+----------+------+------+---------+
|#   |@RID |@CLASS    |legajo|nombre|apellido |
+----+-----+----------+------+------+---------+
|0   |#23:1|Estudiante|3     |Carlos|Rodriguez|
|1   |#25:1|Estudiante|1     |Juan  |Perez    |
+----+-----+----------+------+------+---------+

2 item(s) found. Query executed in 0.001 sec(s).
----

== Conclusiones