= Bases de datos II - OrientDB
v1, {docdate}
:toc:
:title-page:
:toc-title: Secciones
:numbered:
:source-highlighter: highlight.js
:tabsize: 4
:nofooter:
:pdf-page-margin: [3cm, 3cm, 3cm, 3cm]

== Introducción

OrientDB es una bases de datos NoSQL de código abierto orientado a documentos y grafos desarrollada en Java.

== Origen

Fue desarrollado por OrientDB Ltd. y está diseñado para ser una base de datos NoSQL de alto rendimiento y escalable.

== Casos de éxito

== Características principales

- Taxonomía: OrientDB es multi-modelo, lo que significa que admite múltiples modelos de datos, incluyendo documentos, grafos, clave-valor y objetos.

- Escalabilidad: OrientDB es escalable y puede funcionar en un clúster distribuido, lo que permite la distribución de datos en varios nodos para manejar grandes volúmenes de información.

- Transacciones ACID: OrientDB garantiza transacciones ACID (Atomicidad, Consistencia, Aislamiento y Durabilidad), lo que lo hace adecuado para aplicaciones que requieren alta integridad de datos.

- Compatibilidad: OrientDB es compatible con múltiples lenguajes de programación, incluyendo Java, Python y .NET.

== Diferencias con otras bases de datos

== Descarga e instalación

Descargue OrientDB desde la siguiente URL:

https://orientdb.org/download

Se descargará el archivo de la versión community. Descomprímalo en su sistema de archivos y abra un shell en el directorio.

Ahora ingrese a la carpeta que se descomprimió y a la subcarpeta "bin":

[source]
----
cd orientdb-community-3.2.24/bin
----

(cambia el nombre de la carpeta con la versión exacta que descargaste)

y luego, si estás en Linux/OSX, puede iniciar el servidor con `./server.sh`.

Si estás en Windows, inicia el servidor con `server.bat`.

Verás que el servidor inicia:

[source, console]
----
           .
          .`        `
          ,      `:.
         `,`    ,:`
         .,.   :,,
         .,,  ,,,
    .    .,.:::::  ````                                 :::::::::     :::::::::
    ,`   .::,,,,::.,,,,,,`;;                      .:    ::::::::::    :::    :::
    `,.  ::,,,,,,,:.,,.`  `                       .:    :::      :::  :::     :::
     ,,:,:,,,,,,,,::.   `        `         ``     .:    :::      :::  :::     :::
      ,,:.,,,,,,,,,: `::, ,,   ::,::`   : :,::`  ::::   :::      :::  :::    :::
       ,:,,,,,,,,,,::,:   ,,  :.    :   ::    :   .:    :::      :::  :::::::
        :,,,,,,,,,,:,::   ,,  :      :  :     :   .:    :::      :::  :::::::::
  `     :,,,,,,,,,,:,::,  ,, .::::::::  :     :   .:    :::      :::  :::     :::
  `,...,,:,,,,,,,,,: .:,. ,, ,,         :     :   .:    :::      :::  :::     :::
    .,,,,::,,,,,,,:  `: , ,,  :     `   :     :   .:    :::      :::  :::     :::
      ...,::,,,,::.. `:  .,,  :,    :   :     :   .:    :::::::::::   :::     :::
           ,::::,,,. `:   ,,   :::::    :     :   .:    :::::::::     ::::::::::
           ,,:` `,,.
          ,,,    .,`
         ,,.     `,
       ``        `.
                 ``                                         www.orientdb.com
                 `

2023-11-04 16:47:51:200 INFO  Windows OS is detected, 262144 limit of open files will be set for the disk cache. [ONative]
2023-11-04 16:47:51:232 INFO  Loading configuration from: C:/Users/Gonza/Desktop/orientdb-community-3.2.24/config/orientdb-server-config.xml... [OServerConfigurationLoaderXml]
2023-11-04 16:47:51:419 INFO  OrientDB Server v3.2.24 (build ${buildNumber}, branch UNKNOWN) is starting up... [OServer]
2023-11-04 16:47:51:732 INFO  14963257344 B/14270 MB/13 GB of physical memory were detected on machine [ONative]
2023-11-04 16:47:51:732 INFO  Detected memory limit for current process is 14963257344 B/14270 MB/13 GB [ONative]
2023-11-04 16:47:51:732 INFO  JVM can use maximum 2048MB of heap memory [OMemoryAndLocalPaginatedEnginesInitializer]
2023-11-04 16:47:51:732 INFO  Because OrientDB is running outside a container 2g of memory will be left unallocated according to the setting 'memory.leftToOS' not taking into account heap memory [OMemoryAndLocalPaginatedEnginesInitializer]
2023-11-04 16:47:51:732 INFO  OrientDB auto-config DISKCACHE=10,174MB (heap=2,048MB os=14,270MB) [orientechnologies]
2023-11-04 16:47:51:732 INFO  System is started under an effective user : `Gonza` [OEngineLocalPaginated]
2023-11-04 16:47:51:903 INFO  WAL maximum segment size is set to 6,144 MB [OrientDBDistributed]
2023-11-04 16:47:51:997 INFO  Databases directory: C:\Users\Gonza\Desktop\orientdb-community-3.2.24\databases [OServer]
2023-11-04 16:47:52:013 INFO  Creating the system database 'OSystem' for current server [OSystemDatabase]
2023-11-04 16:47:52:060 INFO  Page size for WAL located in C:\Users\Gonza\Desktop\orientdb-community-3.2.24\databases\OSystem is set to 4096 bytes. [CASDiskWriteAheadLog]
2023-11-04 16:47:52:107 INFO  DWL:OSystem: block size = 4096 bytes, maximum segment size = 2161 MB [DoubleWriteLogGL]
2023-11-04 16:47:52:310 INFO  Storage 'plocal:C:\Users\Gonza\Desktop\orientdb-community-3.2.24\databases/OSystem' is created under OrientDB distribution : 3.2.24 (build ${buildNumber}, branch UNKNOWN) [OLocalPaginatedStorage]
2023-11-04 16:47:53:512 INFO  Listening binary connections on 0.0.0.0:2424 (protocol v.38, socket=default) [OServerNetworkListener]
2023-11-04 16:47:53:512 INFO  Listening http connections on 0.0.0.0:2480 (protocol v.10, socket=default) [OServerNetworkListener]

+---------------------------------------------------------------+
|                WARNING: FIRST RUN CONFIGURATION               |
+---------------------------------------------------------------+
| This is the first time the server is running. Please type a   |
| password of your choice for the 'root' user or leave it blank |
| to auto-generate it.                                          |
|                                                               |
| To avoid this message set the environment variable or JVM     |
| setting ORIENTDB_ROOT_PASSWORD to the root password to use.   |
+---------------------------------------------------------------+

Root password [BLANK=auto generate it]: *
----

Luego, deberás ingresar una nueva contraseña para el usuario `root`.

== Conexiones de bases de datos

Existen dos métodos para conectarse a un servidor y comenzar a trabajar con las bases de datos en OrientDB:

1. Acceso a través del navegador en el puerto 2480 (http://localhost:2480/): Esta opción no solo te permite crear y administrar bases de datos, sino también editar y visualizar gráficos directamente desde la página web.

2. Utilización de la consola de OrientDB.

=== Conexión mediante consola

Si estás utilizando Linux/OSX, puedes iniciar la consola ejecutando `./console.sh` desde la carpeta "bin".

En el caso de Windows, inicia la consola ejecutando `console.bat`.

Luego, para conectarte al servidor, puedes usar el siguiente comando (asegúrate de reemplazar `servidor`, `usuario` y `contraseña`):

[source]
----
connect remote:servidor usuario contraseña
----

Para crear una base de datos, utiliza el comando `create database` (recuerda reemplazar `servidor`, `base_de_datos` y `usuario`):

[source]
----
create database plocal:servidor/base_de_datos usuario
----

Para listar las bases de datos existentes, ejecuta el siguiente comando:

[source]
----
list databases
----

Para conectarte a una base de datos, puedes utilizar el siguiente comando:

[source]
----
connect remote:servidor/base_de_datos usuario
----

Asegúrate de reemplazar `servidor`, `base_de_datos` y `usuario` con los valores correspondientes.

Para ver las clases existentes, utiliza el siguiente comando:

[source]
----
classes
----

== Operaciones básicas

OrientDB es compatible con el conocido lenguaje de consultas SQL y soporta consultas en lenguaje Gremlin para trabajar con datos de grafo.

=== Creación de clases

A la hora de crear clases en OrientDB, puedes hacerlo de diversas formas:

.Creación de una clase genérica
[source, sql]
----
CREATE CLASS Estudiante;
----

.Creación de una clase que hereda de un vértice
[source, sql]
----
CREATE CLASS Usuario EXTENDS V;
----

.Creación de una clase que hereda de una arista
[source, sql]
----
CREATE CLASS Sigue EXTENDS E;
----

=== Creación de atributos

Si deseas agregar atributos a una clase antes de ingresar datos, puedes hacerlo de la siguiente manera:

[source, sql]
----
CREATE PROPERTY Estudiante.legajo STRING;
CREATE PROPERTY Estudiante.nombre STRING;
CREATE PROPERTY Estudiante.apellido STRING;
CREATE PROPERTY Estudiante.nacimiento DATE;
----

=== Creación de indices

Para crear indices puedes hacerlo de la siguiente forma:

[source, sql]
----
CREATE INDEX Estudiante.legajo UNIQUE;
----

=== Inserción de Datos

La inserción de datos en OrientDB se puede realizar de diversas formas, similar a como se hace en una base de datos SQL:

Inserción utilizando la sintaxis de columnas y valores:

[source, sql]
----
INSERT INTO Estudiante (legajo, nombre, apellido) VALUES (1, 'Juan', 'Perez');
----

Otra forma de inserción, utilizando la sintaxis de pares clave-valor:

[source, sql]
----
INSERT INTO Estudiante SET legajo = 1, nombre = 'Juan', apellido = 'Perez';
----

También puedes utilizar la sintaxis de contenido JSON para la inserción de datos:

[source, sql]
----
INSERT INTO Estudiante CONTENT {'legajo': 1, 'nombre': 'Juan', 'apellido': 'Perez'};
----

=== Eliminación de Datos

La eliminación de datos en OrientDB se asemeja a la que se realiza en SQL.

A continuación, se presenta un ejemplo que ilustra cómo eliminar datos.

Agreguemos dos estudiantes más a la clase `Estudiante`:

[source, sql]
----
INSERT INTO Estudiante CONTENT {'legajo': 2, 'nombre': 'Maria', 'apellido': 'Gonzalez'};
INSERT INTO Estudiante CONTENT {'legajo': 3, 'nombre': 'Carlos', 'apellido': 'Ramirez'};
----

Al ejecutar una consulta `SELECT * FROM Estudiante`, obtenemos los siguientes resultados en la consola:

[source, console]
----
+----+-----+----------+------+------+--------+
|#   |@RID |@CLASS    |legajo|nombre|apellido|
+----+-----+----------+------+------+--------+
|0   |#22:2|Estudiante|2     |Maria |Gonzalez|
|1   |#23:1|Estudiante|3     |Carlos|Ramirez |
|2   |#25:1|Estudiante|1     |Juan  |Perez   |
+----+-----+----------+------+------+--------+
----

Para eliminar un estudiante con un legajo específico, como el estudiante con legajo igual a 2 (Carlos Ramirez), utilizamos el siguiente comando:

[source, sql]
----
DELETE FROM Estudiante WHERE legajo = 2;
----

Tras la eliminación, al ejecutar nuevamente la consulta `SELECT * FROM Estudiante`, observamos que el estudiante Carlos Ramirez ha sido eliminado:

[source, console]
----
+----+-----+----------+------+------+--------+
|#   |@RID |@CLASS    |legajo|nombre|apellido|
+----+-----+----------+------+------+--------+
|0   |#23:1|Estudiante|3     |Carlos|Ramirez |
|1   |#25:1|Estudiante|1     |Juan  |Perez   |
+----+-----+----------+------+------+--------+
----

=== Actualización de Datos

La actualización de datos en OrientDB se logra utilizando el comando `UPDATE`, que te permite modificar registros existentes. 

A continuación, se presenta un ejemplo de cómo actualizar datos.

Si ejecutamos la consulta `SELECT * FROM Estudiante` obtenemos los siguientes resultados en la consola:

[source, console]
----
+----+-----+----------+------+------+--------+
|#   |@RID |@CLASS    |legajo|nombre|apellido|
+----+-----+----------+------+------+--------+
|0   |#23:1|Estudiante|3     |Carlos|Ramirez |
|1   |#25:1|Estudiante|1     |Juan  |Perez   |
+----+-----+----------+------+------+--------+
----

Para actualizar un registro, utilizamos el comando `UPDATE`. En este ejemplo, cambiamos el apellido de Carlos Ramirez a 'Rodriguez' con la siguiente consulta:

[source, sql]
----
UPDATE Estudiante SET apellido = 'Rodriguez' WHERE legajo = 3;
----

Al ejecutar nuevamente la consulta `SELECT * FROM Estudiante`, observamos los siguientes resultados en la consola:

[source, console]
----
+----+-----+----------+------+------+---------+
|#   |@RID |@CLASS    |legajo|nombre|apellido |
+----+-----+----------+------+------+---------+
|0   |#23:1|Estudiante|3     |Carlos|Rodriguez|
|1   |#25:1|Estudiante|1     |Juan  |Perez    |
+----+-----+----------+------+------+---------+
----

De esta manera, hemos actualizado el apellido de Carlos Ramirez a 'Rodriguez' en la base de datos.

== Conclusiones